### ISSUE TITLE
Warning issued when Docker daemon is not available

### ISSUE THREAD

**Issue by mdub** [realestate-com-au/dfresh#2]
When `dfresh` can't talk to a Docker daemon, it emits a warning, e.g.

```
$ dfresh resolve alpine:3.4
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
alpine:3.4@sha256:36fbf18a36d0410de46201a76b7cfb1d69d44a8f407d6a0814517247b896f8e9
```

**Comment by ghost** [comment]
Why is the engine involved at all? Take the reference `alpine:latest`. In this case, the registry is not specified. It's a relative reference to a registry, like a relative path in a URL, which gets expanded to `docker.io/alpine:latest`. In the docker client/server model, it's the engine that's responsible for the default registry, so the client attempts to ask it for the default.

By cutting the cord with the engine, our client becomes the source of truth for this default registry. For Docker's distribution of moby, it's safe to assume the default registry is dockerhub. It seems that there cases where a variant is used. RHEL's project atomic carry's a patch [Add-add-registry-and-block-registry-options-to-docker.patch](http://www.projectatomic.io/docs/docker_patches/) where the default registry is altered:

> We also want to have Red Hat Content available from our Registry by default.
