### ISSUE TITLE
Need a way for dfresh to tell us what is outdated

### ISSUE THREAD

**Issue by tigris** [realestate-com-au/dfresh#6]
Similar to `bundle outdated`, or `tagfish update --dry-run`, it'd be nice if there was a non-destructive way to point `dfresh` at a particular `Dockerfile` and have it simply tell us what's outdated rather than acting on it immediately.

**Comment by mdub** [comment]
Good idea.

I'm not sure I like "outdated" as the command-name, though. It would draw comparison to `bundle outdated`, and I find the exit-status of that command misleading and wrong:

```
$ if bundle outdated; then echo OUT OF DATE; else echo UP TO DATE; fi
Outdated gems included in the bundle:
  * slop (newest 4.5.0, installed 3.6.0)
UP TO DATE
```

Wat?

So, let's use a different word. How about "uptodate", or "check"?

If something was out-of-date, it prints details, and returns non-zero:

```
$ dfresh uptodate Dockerfile
Dockerfile:1: ruby:2.4-alpine@sha256:ead6b812ae745761a90c8900eae672b8d7e952e3464a92f3e977b073e4f91f1a (was sha256:44cc13ef72b7aa1e979dd115805548c50cb2ddc52bb21eb9b8a9ea65df09ddcf)
$ echo $?
1
```

But if everything was up-to-date, it returns success:

```
$ dfresh uptodate Dockerfile
$ echo $?
0
```

**Comment by mdub** [comment]
More readable would be:

```
Dockerfile:1: ruby:2.4-alpine
  was sha256:44cc13ef72b7aa1e979dd115805548c50cb2ddc52bb21eb9b8a9ea65df09ddcf
  now sha256:ead6b812ae745761a90c8900eae672b8d7e952e3464a92f3e977b073e4f91f1a
```

**Comment by mdub** [comment]
Implemented now: `dfresh check ...`
